<?php

namespace Amz\Orders\Model;

use OpenAPI\Runtime\AbstractModel;

/**
 * Contains information regarding the Shipping Settings Automation program, such as
 * whether the order's shipping settings were generated automatically, and what
 * those settings are.
 */
class AutomatedShippingSettings extends AbstractModel
{
    /**
     * If true, this order has automated shipping settings generated by Amazon. This
     * order could be identified as an SSA order.
     *
     * @var bool
     */
    public $HasAutomatedShippingSettings = null;

    /**
     * Auto-generated carrier for SSA orders.
     *
     * @var string
     */
    public $AutomatedCarrier = null;

    /**
     * Auto-generated ship method for SSA orders.
     *
     * @var string
     */
    public $AutomatedShipMethod = null;
}
