<?php

namespace Amz\Orders;

use OpenAPI\Runtime\ResponseTypes as AbstractResponseTypes;

class ResponseTypes extends AbstractResponseTypes
{
    public static $types = [
        'searchContentDocuments' => [
            '200.' => 'Amz\\AplusContent\\Model\\SearchContentDocumentsResponse',
            '400.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '401.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '403.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '404.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '410.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '429.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '500.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '503.' => 'Amz\\AplusContent\\Model\\ErrorList',
        ],
        'createContentDocument' => [
            '200.' => 'Amz\\AplusContent\\Model\\PostContentDocumentResponse',
            '400.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '401.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '403.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '404.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '429.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '500.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '503.' => 'Amz\\AplusContent\\Model\\ErrorList',
        ],
        'getContentDocument' => [
            '200.' => 'Amz\\AplusContent\\Model\\GetContentDocumentResponse',
            '400.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '401.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '403.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '404.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '410.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '429.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '500.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '503.' => 'Amz\\AplusContent\\Model\\ErrorList',
        ],
        'updateContentDocument' => [
            '200.' => 'Amz\\AplusContent\\Model\\PostContentDocumentResponse',
            '400.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '401.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '403.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '404.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '410.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '429.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '500.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '503.' => 'Amz\\AplusContent\\Model\\ErrorList',
        ],
        'listContentDocumentAsinRelations' => [
            '200.' => 'Amz\\AplusContent\\Model\\ListContentDocumentAsinRelationsResponse',
            '400.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '401.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '403.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '404.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '410.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '429.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '500.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '503.' => 'Amz\\AplusContent\\Model\\ErrorList',
        ],
        'postContentDocumentAsinRelations' => [
            '200.' => 'Amz\\AplusContent\\Model\\PostContentDocumentAsinRelationsResponse',
            '400.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '401.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '403.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '404.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '410.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '429.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '500.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '503.' => 'Amz\\AplusContent\\Model\\ErrorList',
        ],
        'validateContentDocumentAsinRelations' => [
            '200.' => 'Amz\\AplusContent\\Model\\ValidateContentDocumentAsinRelationsResponse',
            '400.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '401.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '403.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '404.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '429.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '500.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '503.' => 'Amz\\AplusContent\\Model\\ErrorList',
        ],
        'searchContentPublishRecords' => [
            '200.' => 'Amz\\AplusContent\\Model\\SearchContentPublishRecordsResponse',
            '400.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '401.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '403.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '404.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '429.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '500.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '503.' => 'Amz\\AplusContent\\Model\\ErrorList',
        ],
        'postContentDocumentApprovalSubmission' => [
            '200.' => 'Amz\\AplusContent\\Model\\PostContentDocumentApprovalSubmissionResponse',
            '400.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '401.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '403.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '404.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '410.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '429.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '500.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '503.' => 'Amz\\AplusContent\\Model\\ErrorList',
        ],
        'postContentDocumentSuspendSubmission' => [
            '200.' => 'Amz\\AplusContent\\Model\\PostContentDocumentSuspendSubmissionResponse',
            '400.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '401.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '403.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '404.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '410.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '429.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '500.' => 'Amz\\AplusContent\\Model\\ErrorList',
            '503.' => 'Amz\\AplusContent\\Model\\ErrorList',
        ],
        'getAuthorizationCode' => [
            '200.' => 'Amz\\Authorization\\Model\\GetAuthorizationCodeResponse',
            '400.' => 'Amz\\Authorization\\Model\\GetAuthorizationCodeResponse',
            '403.' => 'Amz\\Authorization\\Model\\GetAuthorizationCodeResponse',
            '404.' => 'Amz\\Authorization\\Model\\GetAuthorizationCodeResponse',
            '413.' => 'Amz\\Authorization\\Model\\GetAuthorizationCodeResponse',
            '415.' => 'Amz\\Authorization\\Model\\GetAuthorizationCodeResponse',
            '429.' => 'Amz\\Authorization\\Model\\GetAuthorizationCodeResponse',
            '500.' => 'Amz\\Authorization\\Model\\GetAuthorizationCodeResponse',
            '503.' => 'Amz\\Authorization\\Model\\GetAuthorizationCodeResponse',
        ],
        'listCatalogItems' => [
            '200.' => 'Amz\\CatalogItems\\Model\\ListCatalogItemsResponse',
            '400.' => 'Amz\\CatalogItems\\Model\\ListCatalogItemsResponse',
            '401.' => 'Amz\\CatalogItems\\Model\\ListCatalogItemsResponse',
            '403.' => 'Amz\\CatalogItems\\Model\\ListCatalogItemsResponse',
            '404.' => 'Amz\\CatalogItems\\Model\\ListCatalogItemsResponse',
            '429.' => 'Amz\\CatalogItems\\Model\\ListCatalogItemsResponse',
            '500.' => 'Amz\\CatalogItems\\Model\\ListCatalogItemsResponse',
            '503.' => 'Amz\\CatalogItems\\Model\\ListCatalogItemsResponse',
        ],
        'getCatalogItem' => [
            '200.' => 'Amz\\CatalogItems\\Model\\Item',
            '400.' => 'Amz\\CatalogItems\\Model\\ErrorList',
            '401.' => 'Amz\\CatalogItems\\Model\\GetCatalogItemResponse',
            '403.' => 'Amz\\CatalogItems\\Model\\ErrorList',
            '404.' => 'Amz\\CatalogItems\\Model\\ErrorList',
            '429.' => 'Amz\\CatalogItems\\Model\\ErrorList',
            '500.' => 'Amz\\CatalogItems\\Model\\ErrorList',
            '503.' => 'Amz\\CatalogItems\\Model\\ErrorList',
            '413.' => 'Amz\\CatalogItems\\Model\\ErrorList',
            '415.' => 'Amz\\CatalogItems\\Model\\ErrorList',
        ],
        'listCatalogCategories' => [
            '200.' => 'Amz\\CatalogItems\\Model\\ListCatalogCategoriesResponse',
            '400.' => 'Amz\\CatalogItems\\Model\\ListCatalogCategoriesResponse',
            '401.' => 'Amz\\CatalogItems\\Model\\ListCatalogCategoriesResponse',
            '403.' => 'Amz\\CatalogItems\\Model\\ListCatalogCategoriesResponse',
            '404.' => 'Amz\\CatalogItems\\Model\\ListCatalogCategoriesResponse',
            '429.' => 'Amz\\CatalogItems\\Model\\ListCatalogCategoriesResponse',
            '500.' => 'Amz\\CatalogItems\\Model\\ListCatalogCategoriesResponse',
            '503.' => 'Amz\\CatalogItems\\Model\\ListCatalogCategoriesResponse',
        ],
        'searchCatalogItems' => [
            '200.' => 'Amz\\CatalogItems\\Model\\ItemSearchResults',
            '400.' => 'Amz\\CatalogItems\\Model\\ErrorList',
            '403.' => 'Amz\\CatalogItems\\Model\\ErrorList',
            '404.' => 'Amz\\CatalogItems\\Model\\ErrorList',
            '413.' => 'Amz\\CatalogItems\\Model\\ErrorList',
            '415.' => 'Amz\\CatalogItems\\Model\\ErrorList',
            '429.' => 'Amz\\CatalogItems\\Model\\ErrorList',
            '500.' => 'Amz\\CatalogItems\\Model\\ErrorList',
            '503.' => 'Amz\\CatalogItems\\Model\\ErrorList',
        ],
        'getItemEligibilityPreview' => [
            '200.' => 'Amz\\FbaInboundEligibility\\Model\\GetItemEligibilityPreviewResponse',
            '400.' => 'Amz\\FbaInboundEligibility\\Model\\GetItemEligibilityPreviewResponse',
            '401.' => 'Amz\\FbaInboundEligibility\\Model\\GetItemEligibilityPreviewResponse',
            '403.' => 'Amz\\FbaInboundEligibility\\Model\\GetItemEligibilityPreviewResponse',
            '404.' => 'Amz\\FbaInboundEligibility\\Model\\GetItemEligibilityPreviewResponse',
            '429.' => 'Amz\\FbaInboundEligibility\\Model\\GetItemEligibilityPreviewResponse',
            '500.' => 'Amz\\FbaInboundEligibility\\Model\\GetItemEligibilityPreviewResponse',
            '503.' => 'Amz\\FbaInboundEligibility\\Model\\GetItemEligibilityPreviewResponse',
        ],
        'getInventorySummaries' => [
            '200.' => 'Amz\\FbaInventory\\Model\\GetInventorySummariesResponse',
            '400.' => 'Amz\\FbaInventory\\Model\\GetInventorySummariesResponse',
            '403.' => 'Amz\\FbaInventory\\Model\\GetInventorySummariesResponse',
            '404.' => 'Amz\\FbaInventory\\Model\\GetInventorySummariesResponse',
            '429.' => 'Amz\\FbaInventory\\Model\\GetInventorySummariesResponse',
            '500.' => 'Amz\\FbaInventory\\Model\\GetInventorySummariesResponse',
            '503.' => 'Amz\\FbaInventory\\Model\\GetInventorySummariesResponse',
        ],
        'getSmallAndLightEnrollmentBySellerSKU' => [
            '200.' => 'Amz\\FbaSmallAndLight\\Model\\SmallAndLightEnrollment',
            '400.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '403.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '404.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '413.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '415.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '429.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '500.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '503.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
        ],
        'putSmallAndLightEnrollmentBySellerSKU' => [
            '200.' => 'Amz\\FbaSmallAndLight\\Model\\SmallAndLightEnrollment',
            '400.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '403.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '404.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '413.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '415.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '429.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '500.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '503.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
        ],
        'deleteSmallAndLightEnrollmentBySellerSKU' => [
            '400.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '403.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '404.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '413.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '415.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '429.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '500.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '503.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
        ],
        'getSmallAndLightEligibilityBySellerSKU' => [
            '200.' => 'Amz\\FbaSmallAndLight\\Model\\SmallAndLightEligibility',
            '400.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '403.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '404.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '413.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '415.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '429.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '500.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '503.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
        ],
        'getSmallAndLightFeePreview' => [
            '200.' => 'Amz\\FbaSmallAndLight\\Model\\SmallAndLightFeePreviews',
            '400.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '401.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '403.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '404.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '429.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '500.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
            '503.' => 'Amz\\FbaSmallAndLight\\Model\\ErrorList',
        ],
        'getFeeds' => [
            '200.' => 'Amz\\Feeds\\Model\\GetFeedsResponse',
            '400.' => 'Amz\\Feeds\\Model\\ErrorList',
            '401.' => 'Amz\\Feeds\\Model\\ErrorList',
            '403.' => 'Amz\\Feeds\\Model\\ErrorList',
            '404.' => 'Amz\\Feeds\\Model\\ErrorList',
            '415.' => 'Amz\\Feeds\\Model\\ErrorList',
            '429.' => 'Amz\\Feeds\\Model\\ErrorList',
            '500.' => 'Amz\\Feeds\\Model\\ErrorList',
            '503.' => 'Amz\\Feeds\\Model\\ErrorList',
        ],
        'createFeed' => [
            '202.' => 'Amz\\Feeds\\Model\\CreateFeedResponse',
            '400.' => 'Amz\\Feeds\\Model\\ErrorList',
            '401.' => 'Amz\\Feeds\\Model\\ErrorList',
            '403.' => 'Amz\\Feeds\\Model\\ErrorList',
            '404.' => 'Amz\\Feeds\\Model\\ErrorList',
            '415.' => 'Amz\\Feeds\\Model\\ErrorList',
            '429.' => 'Amz\\Feeds\\Model\\ErrorList',
            '500.' => 'Amz\\Feeds\\Model\\ErrorList',
            '503.' => 'Amz\\Feeds\\Model\\ErrorList',
        ],
        'getFeed' => [
            '200.' => 'Amz\\Feeds\\Model\\Feed',
            '400.' => 'Amz\\Feeds\\Model\\ErrorList',
            '401.' => 'Amz\\Feeds\\Model\\ErrorList',
            '403.' => 'Amz\\Feeds\\Model\\ErrorList',
            '404.' => 'Amz\\Feeds\\Model\\ErrorList',
            '415.' => 'Amz\\Feeds\\Model\\ErrorList',
            '429.' => 'Amz\\Feeds\\Model\\ErrorList',
            '500.' => 'Amz\\Feeds\\Model\\ErrorList',
            '503.' => 'Amz\\Feeds\\Model\\ErrorList',
        ],
        'cancelFeed' => [
            '200.' => 'Amz\\Feeds\\Model\\CancelFeedResponse',
            '400.' => 'Amz\\Feeds\\Model\\ErrorList',
            '401.' => 'Amz\\Feeds\\Model\\ErrorList',
            '403.' => 'Amz\\Feeds\\Model\\ErrorList',
            '404.' => 'Amz\\Feeds\\Model\\ErrorList',
            '415.' => 'Amz\\Feeds\\Model\\ErrorList',
            '429.' => 'Amz\\Feeds\\Model\\ErrorList',
            '500.' => 'Amz\\Feeds\\Model\\ErrorList',
            '503.' => 'Amz\\Feeds\\Model\\ErrorList',
        ],
        'createFeedDocument' => [
            '201.' => 'Amz\\Feeds\\Model\\CreateFeedDocumentResponse',
            '400.' => 'Amz\\Feeds\\Model\\ErrorList',
            '403.' => 'Amz\\Feeds\\Model\\ErrorList',
            '404.' => 'Amz\\Feeds\\Model\\ErrorList',
            '413.' => 'Amz\\Feeds\\Model\\ErrorList',
            '415.' => 'Amz\\Feeds\\Model\\ErrorList',
            '429.' => 'Amz\\Feeds\\Model\\ErrorList',
            '500.' => 'Amz\\Feeds\\Model\\ErrorList',
            '503.' => 'Amz\\Feeds\\Model\\ErrorList',
        ],
        'getFeedDocument' => [
            '200.' => 'Amz\\Feeds\\Model\\FeedDocument',
            '400.' => 'Amz\\Feeds\\Model\\ErrorList',
            '401.' => 'Amz\\Feeds\\Model\\ErrorList',
            '403.' => 'Amz\\Feeds\\Model\\ErrorList',
            '404.' => 'Amz\\Feeds\\Model\\ErrorList',
            '415.' => 'Amz\\Feeds\\Model\\ErrorList',
            '429.' => 'Amz\\Feeds\\Model\\ErrorList',
            '500.' => 'Amz\\Feeds\\Model\\ErrorList',
            '503.' => 'Amz\\Feeds\\Model\\ErrorList',
        ],
        'listFinancialEventGroups' => [
            '200.' => 'Amz\\Finances\\Model\\ListFinancialEventGroupsResponse',
            '400.' => 'Amz\\Finances\\Model\\ListFinancialEventGroupsResponse',
            '403.' => 'Amz\\Finances\\Model\\ListFinancialEventGroupsResponse',
            '404.' => 'Amz\\Finances\\Model\\ListFinancialEventGroupsResponse',
            '429.' => 'Amz\\Finances\\Model\\ListFinancialEventGroupsResponse',
            '500.' => 'Amz\\Finances\\Model\\ListFinancialEventGroupsResponse',
            '503.' => 'Amz\\Finances\\Model\\ListFinancialEventGroupsResponse',
        ],
        'listFinancialEventsByGroupId' => [
            '200.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '400.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '403.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '404.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '429.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '500.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '503.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
        ],
        'listFinancialEventsByOrderId' => [
            '200.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '400.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '403.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '404.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '429.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '500.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '503.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
        ],
        'listFinancialEvents' => [
            '200.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '400.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '403.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '404.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '429.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '500.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
            '503.' => 'Amz\\Finances\\Model\\ListFinancialEventsResponse',
        ],
        'getInboundGuidance' => [
            '200.' => 'Amz\\FulfillmentInbound\\Model\\GetInboundGuidanceResponse',
            '400.' => 'Amz\\FulfillmentInbound\\Model\\GetInboundGuidanceResponse',
            '401.' => 'Amz\\FulfillmentInbound\\Model\\GetInboundGuidanceResponse',
            '403.' => 'Amz\\FulfillmentInbound\\Model\\GetInboundGuidanceResponse',
            '404.' => 'Amz\\FulfillmentInbound\\Model\\GetInboundGuidanceResponse',
            '429.' => 'Amz\\FulfillmentInbound\\Model\\GetInboundGuidanceResponse',
            '500.' => 'Amz\\FulfillmentInbound\\Model\\GetInboundGuidanceResponse',
            '503.' => 'Amz\\FulfillmentInbound\\Model\\GetInboundGuidanceResponse',
        ],
        'createInboundShipmentPlan' => [
            '200.' => 'Amz\\FulfillmentInbound\\Model\\CreateInboundShipmentPlanResponse',
            '400.' => 'Amz\\FulfillmentInbound\\Model\\CreateInboundShipmentPlanResponse',
            '401.' => 'Amz\\FulfillmentInbound\\Model\\CreateInboundShipmentPlanResponse',
            '403.' => 'Amz\\FulfillmentInbound\\Model\\CreateInboundShipmentPlanResponse',
            '404.' => 'Amz\\FulfillmentInbound\\Model\\CreateInboundShipmentPlanResponse',
            '429.' => 'Amz\\FulfillmentInbound\\Model\\CreateInboundShipmentPlanResponse',
            '500.' => 'Amz\\FulfillmentInbound\\Model\\CreateInboundShipmentPlanResponse',
            '503.' => 'Amz\\FulfillmentInbound\\Model\\CreateInboundShipmentPlanResponse',
        ],
        'updateInboundShipment' => [
            '200.' => 'Amz\\FulfillmentInbound\\Model\\InboundShipmentResponse',
            '400.' => 'Amz\\FulfillmentInbound\\Model\\InboundShipmentResponse',
            '401.' => 'Amz\\FulfillmentInbound\\Model\\InboundShipmentResponse',
            '403.' => 'Amz\\FulfillmentInbound\\Model\\InboundShipmentResponse',
            '404.' => 'Amz\\FulfillmentInbound\\Model\\InboundShipmentResponse',
            '429.' => 'Amz\\FulfillmentInbound\\Model\\InboundShipmentResponse',
            '500.' => 'Amz\\FulfillmentInbound\\Model\\InboundShipmentResponse',
            '503.' => 'Amz\\FulfillmentInbound\\Model\\InboundShipmentResponse',
        ],
        'createInboundShipment' => [
            '200.' => 'Amz\\FulfillmentInbound\\Model\\InboundShipmentResponse',
            '400.' => 'Amz\\FulfillmentInbound\\Model\\InboundShipmentResponse',
            '401.' => 'Amz\\FulfillmentInbound\\Model\\InboundShipmentResponse',
            '403.' => 'Amz\\FulfillmentInbound\\Model\\InboundShipmentResponse',
            '404.' => 'Amz\\FulfillmentInbound\\Model\\InboundShipmentResponse',
            '429.' => 'Amz\\FulfillmentInbound\\Model\\InboundShipmentResponse',
            '500.' => 'Amz\\FulfillmentInbound\\Model\\InboundShipmentResponse',
            '503.' => 'Amz\\FulfillmentInbound\\Model\\InboundShipmentResponse',
        ],
        'getPreorderInfo' => [
            '200.' => 'Amz\\FulfillmentInbound\\Model\\GetPreorderInfoResponse',
            '400.' => 'Amz\\FulfillmentInbound\\Model\\GetPreorderInfoResponse',
            '401.' => 'Amz\\FulfillmentInbound\\Model\\GetPreorderInfoResponse',
            '403.' => 'Amz\\FulfillmentInbound\\Model\\GetPreorderInfoResponse',
            '404.' => 'Amz\\FulfillmentInbound\\Model\\GetPreorderInfoResponse',
            '429.' => 'Amz\\FulfillmentInbound\\Model\\GetPreorderInfoResponse',
            '500.' => 'Amz\\FulfillmentInbound\\Model\\GetPreorderInfoResponse',
            '503.' => 'Amz\\FulfillmentInbound\\Model\\GetPreorderInfoResponse',
        ],
        'confirmPreorder' => [
            '200.' => 'Amz\\FulfillmentInbound\\Model\\ConfirmPreorderResponse',
            '400.' => 'Amz\\FulfillmentInbound\\Model\\ConfirmPreorderResponse',
            '401.' => 'Amz\\FulfillmentInbound\\Model\\ConfirmPreorderResponse',
            '403.' => 'Amz\\FulfillmentInbound\\Model\\ConfirmPreorderResponse',
            '404.' => 'Amz\\FulfillmentInbound\\Model\\ConfirmPreorderResponse',
            '429.' => 'Amz\\FulfillmentInbound\\Model\\ConfirmPreorderResponse',
            '500.' => 'Amz\\FulfillmentInbound\\Model\\ConfirmPreorderResponse',
            '503.' => 'Amz\\FulfillmentInbound\\Model\\ConfirmPreorderResponse',
        ],
        'getPrepInstructions' => [
            '200.' => 'Amz\\FulfillmentInbound\\Model\\GetPrepInstructionsResponse',
            '400.' => 'Amz\\FulfillmentInbound\\Model\\GetPrepInstructionsResponse',
            '401.' => 'Amz\\FulfillmentInbound\\Model\\GetPrepInstructionsResponse',
            '403.' => 'Amz\\FulfillmentInbound\\Model\\GetPrepInstructionsResponse',
            '404.' => 'Amz\\FulfillmentInbound\\Model\\GetPrepInstructionsResponse',
            '429.' => 'Amz\\FulfillmentInbound\\Model\\GetPrepInstructionsResponse',
            '500.' => 'Amz\\FulfillmentInbound\\Model\\GetPrepInstructionsResponse',
            '503.' => 'Amz\\FulfillmentInbound\\Model\\GetPrepInstructionsResponse',
        ],
        'getTransportDetails' => [
            '200.' => 'Amz\\FulfillmentInbound\\Model\\GetTransportDetailsResponse',
            '400.' => 'Amz\\FulfillmentInbound\\Model\\GetTransportDetailsResponse',
            '401.' => 'Amz\\FulfillmentInbound\\Model\\GetTransportDetailsResponse',
            '403.' => 'Amz\\FulfillmentInbound\\Model\\GetTransportDetailsResponse',
            '404.' => 'Amz\\FulfillmentInbound\\Model\\GetTransportDetailsResponse',
            '429.' => 'Amz\\FulfillmentInbound\\Model\\GetTransportDetailsResponse',
            '500.' => 'Amz\\FulfillmentInbound\\Model\\GetTransportDetailsResponse',
            '503.' => 'Amz\\FulfillmentInbound\\Model\\GetTransportDetailsResponse',
        ],
        'putTransportDetails' => [
            '200.' => 'Amz\\FulfillmentInbound\\Model\\PutTransportDetailsResponse',
            '400.' => 'Amz\\FulfillmentInbound\\Model\\PutTransportDetailsResponse',
            '401.' => 'Amz\\FulfillmentInbound\\Model\\PutTransportDetailsResponse',
            '403.' => 'Amz\\FulfillmentInbound\\Model\\PutTransportDetailsResponse',
            '404.' => 'Amz\\FulfillmentInbound\\Model\\PutTransportDetailsResponse',
            '429.' => 'Amz\\FulfillmentInbound\\Model\\PutTransportDetailsResponse',
            '500.' => 'Amz\\FulfillmentInbound\\Model\\PutTransportDetailsResponse',
            '503.' => 'Amz\\FulfillmentInbound\\Model\\PutTransportDetailsResponse',
        ],
        'voidTransport' => [
            '200.' => 'Amz\\FulfillmentInbound\\Model\\VoidTransportResponse',
            '400.' => 'Amz\\FulfillmentInbound\\Model\\VoidTransportResponse',
            '401.' => 'Amz\\FulfillmentInbound\\Model\\VoidTransportResponse',
            '403.' => 'Amz\\FulfillmentInbound\\Model\\VoidTransportResponse',
            '404.' => 'Amz\\FulfillmentInbound\\Model\\VoidTransportResponse',
            '429.' => 'Amz\\FulfillmentInbound\\Model\\VoidTransportResponse',
            '500.' => 'Amz\\FulfillmentInbound\\Model\\VoidTransportResponse',
            '503.' => 'Amz\\FulfillmentInbound\\Model\\VoidTransportResponse',
        ],
        'estimateTransport' => [
            '200.' => 'Amz\\FulfillmentInbound\\Model\\EstimateTransportResponse',
            '400.' => 'Amz\\FulfillmentInbound\\Model\\EstimateTransportResponse',
            '401.' => 'Amz\\FulfillmentInbound\\Model\\EstimateTransportResponse',
            '403.' => 'Amz\\FulfillmentInbound\\Model\\EstimateTransportResponse',
            '404.' => 'Amz\\FulfillmentInbound\\Model\\EstimateTransportResponse',
            '429.' => 'Amz\\FulfillmentInbound\\Model\\EstimateTransportResponse',
            '500.' => 'Amz\\FulfillmentInbound\\Model\\EstimateTransportResponse',
            '503.' => 'Amz\\FulfillmentInbound\\Model\\EstimateTransportResponse',
        ],
        'confirmTransport' => [
            '200.' => 'Amz\\FulfillmentInbound\\Model\\ConfirmTransportResponse',
            '400.' => 'Amz\\FulfillmentInbound\\Model\\ConfirmTransportResponse',
            '401.' => 'Amz\\FulfillmentInbound\\Model\\ConfirmTransportResponse',
            '403.' => 'Amz\\FulfillmentInbound\\Model\\ConfirmTransportResponse',
            '404.' => 'Amz\\FulfillmentInbound\\Model\\ConfirmTransportResponse',
            '429.' => 'Amz\\FulfillmentInbound\\Model\\ConfirmTransportResponse',
            '500.' => 'Amz\\FulfillmentInbound\\Model\\ConfirmTransportResponse',
            '503.' => 'Amz\\FulfillmentInbound\\Model\\ConfirmTransportResponse',
        ],
        'getLabels' => [
            '200.' => 'Amz\\FulfillmentInbound\\Model\\GetLabelsResponse',
            '400.' => 'Amz\\FulfillmentInbound\\Model\\GetLabelsResponse',
            '401.' => 'Amz\\FulfillmentInbound\\Model\\GetLabelsResponse',
            '403.' => 'Amz\\FulfillmentInbound\\Model\\GetLabelsResponse',
            '404.' => 'Amz\\FulfillmentInbound\\Model\\GetLabelsResponse',
            '429.' => 'Amz\\FulfillmentInbound\\Model\\GetLabelsResponse',
            '500.' => 'Amz\\FulfillmentInbound\\Model\\GetLabelsResponse',
            '503.' => 'Amz\\FulfillmentInbound\\Model\\GetLabelsResponse',
        ],
        'getBillOfLading' => [
            '200.' => 'Amz\\FulfillmentInbound\\Model\\GetBillOfLadingResponse',
            '400.' => 'Amz\\FulfillmentInbound\\Model\\GetBillOfLadingResponse',
            '401.' => 'Amz\\FulfillmentInbound\\Model\\GetBillOfLadingResponse',
            '403.' => 'Amz\\FulfillmentInbound\\Model\\GetBillOfLadingResponse',
            '404.' => 'Amz\\FulfillmentInbound\\Model\\GetBillOfLadingResponse',
            '429.' => 'Amz\\FulfillmentInbound\\Model\\GetBillOfLadingResponse',
            '500.' => 'Amz\\FulfillmentInbound\\Model\\GetBillOfLadingResponse',
            '503.' => 'Amz\\FulfillmentInbound\\Model\\GetBillOfLadingResponse',
        ],
        'getShipments' => [
            '200.' => 'Amz\\FulfillmentInbound\\Model\\GetShipmentsResponse',
            '400.' => 'Amz\\FulfillmentInbound\\Model\\GetShipmentsResponse',
            '401.' => 'Amz\\FulfillmentInbound\\Model\\GetShipmentsResponse',
            '403.' => 'Amz\\FulfillmentInbound\\Model\\GetShipmentsResponse',
            '404.' => 'Amz\\FulfillmentInbound\\Model\\GetShipmentsResponse',
            '429.' => 'Amz\\FulfillmentInbound\\Model\\GetShipmentsResponse',
            '500.' => 'Amz\\FulfillmentInbound\\Model\\GetShipmentsResponse',
            '503.' => 'Amz\\FulfillmentInbound\\Model\\GetShipmentsResponse',
        ],
        'getShipmentItemsByShipmentId' => [
            '200.' => 'Amz\\FulfillmentInbound\\Model\\GetShipmentItemsResponse',
            '400.' => 'Amz\\FulfillmentInbound\\Model\\GetShipmentItemsResponse',
            '401.' => 'Amz\\FulfillmentInbound\\Model\\GetShipmentItemsResponse',
            '403.' => 'Amz\\FulfillmentInbound\\Model\\GetShipmentItemsResponse',
            '404.' => 'Amz\\FulfillmentInbound\\Model\\GetShipmentItemsResponse',
            '429.' => 'Amz\\FulfillmentInbound\\Model\\GetShipmentItemsResponse',
            '500.' => 'Amz\\FulfillmentInbound\\Model\\GetShipmentItemsResponse',
            '503.' => 'Amz\\FulfillmentInbound\\Model\\GetShipmentItemsResponse',
        ],
        'getShipmentItems' => [
            '200.' => 'Amz\\FulfillmentInbound\\Model\\GetShipmentItemsResponse',
            '400.' => 'Amz\\FulfillmentInbound\\Model\\GetShipmentItemsResponse',
            '401.' => 'Amz\\FulfillmentInbound\\Model\\GetShipmentItemsResponse',
            '403.' => 'Amz\\FulfillmentInbound\\Model\\GetShipmentItemsResponse',
            '404.' => 'Amz\\FulfillmentInbound\\Model\\GetShipmentItemsResponse',
            '429.' => 'Amz\\FulfillmentInbound\\Model\\GetShipmentItemsResponse',
            '500.' => 'Amz\\FulfillmentInbound\\Model\\GetShipmentItemsResponse',
            '503.' => 'Amz\\FulfillmentInbound\\Model\\GetShipmentItemsResponse',
        ],
        'getFulfillmentPreview' => [
            '200.' => 'Amz\\FulfillmentOutbound\\Model\\GetFulfillmentPreviewResponse',
            '400.' => 'Amz\\FulfillmentOutbound\\Model\\GetFulfillmentPreviewResponse',
            '401.' => 'Amz\\FulfillmentOutbound\\Model\\GetFulfillmentPreviewResponse',
            '403.' => 'Amz\\FulfillmentOutbound\\Model\\GetFulfillmentPreviewResponse',
            '404.' => 'Amz\\FulfillmentOutbound\\Model\\GetFulfillmentPreviewResponse',
            '429.' => 'Amz\\FulfillmentOutbound\\Model\\GetFulfillmentPreviewResponse',
            '500.' => 'Amz\\FulfillmentOutbound\\Model\\GetFulfillmentPreviewResponse',
            '503.' => 'Amz\\FulfillmentOutbound\\Model\\GetFulfillmentPreviewResponse',
        ],
        'listAllFulfillmentOrders' => [
            '200.' => 'Amz\\FulfillmentOutbound\\Model\\ListAllFulfillmentOrdersResponse',
            '400.' => 'Amz\\FulfillmentOutbound\\Model\\ListAllFulfillmentOrdersResponse',
            '401.' => 'Amz\\FulfillmentOutbound\\Model\\ListAllFulfillmentOrdersResponse',
            '403.' => 'Amz\\FulfillmentOutbound\\Model\\ListAllFulfillmentOrdersResponse',
            '404.' => 'Amz\\FulfillmentOutbound\\Model\\ListAllFulfillmentOrdersResponse',
            '429.' => 'Amz\\FulfillmentOutbound\\Model\\ListAllFulfillmentOrdersResponse',
            '500.' => 'Amz\\FulfillmentOutbound\\Model\\ListAllFulfillmentOrdersResponse',
            '503.' => 'Amz\\FulfillmentOutbound\\Model\\ListAllFulfillmentOrdersResponse',
        ],
        'createFulfillmentOrder' => [
            '200.' => 'Amz\\FulfillmentOutbound\\Model\\CreateFulfillmentOrderResponse',
            '400.' => 'Amz\\FulfillmentOutbound\\Model\\CreateFulfillmentOrderResponse',
            '401.' => 'Amz\\FulfillmentOutbound\\Model\\CreateFulfillmentOrderResponse',
            '403.' => 'Amz\\FulfillmentOutbound\\Model\\CreateFulfillmentOrderResponse',
            '404.' => 'Amz\\FulfillmentOutbound\\Model\\CreateFulfillmentOrderResponse',
            '429.' => 'Amz\\FulfillmentOutbound\\Model\\CreateFulfillmentOrderResponse',
            '500.' => 'Amz\\FulfillmentOutbound\\Model\\CreateFulfillmentOrderResponse',
            '503.' => 'Amz\\FulfillmentOutbound\\Model\\CreateFulfillmentOrderResponse',
        ],
        'getPackageTrackingDetails' => [
            '200.' => 'Amz\\FulfillmentOutbound\\Model\\GetPackageTrackingDetailsResponse',
            '400.' => 'Amz\\FulfillmentOutbound\\Model\\GetPackageTrackingDetailsResponse',
            '401.' => 'Amz\\FulfillmentOutbound\\Model\\GetPackageTrackingDetailsResponse',
            '403.' => 'Amz\\FulfillmentOutbound\\Model\\GetPackageTrackingDetailsResponse',
            '404.' => 'Amz\\FulfillmentOutbound\\Model\\GetPackageTrackingDetailsResponse',
            '429.' => 'Amz\\FulfillmentOutbound\\Model\\GetPackageTrackingDetailsResponse',
            '500.' => 'Amz\\FulfillmentOutbound\\Model\\GetPackageTrackingDetailsResponse',
            '503.' => 'Amz\\FulfillmentOutbound\\Model\\GetPackageTrackingDetailsResponse',
        ],
        'listReturnReasonCodes' => [
            '200.' => 'Amz\\FulfillmentOutbound\\Model\\ListReturnReasonCodesResponse',
            '400.' => 'Amz\\FulfillmentOutbound\\Model\\ListReturnReasonCodesResponse',
            '401.' => 'Amz\\FulfillmentOutbound\\Model\\ListReturnReasonCodesResponse',
            '403.' => 'Amz\\FulfillmentOutbound\\Model\\ListReturnReasonCodesResponse',
            '404.' => 'Amz\\FulfillmentOutbound\\Model\\ListReturnReasonCodesResponse',
            '429.' => 'Amz\\FulfillmentOutbound\\Model\\ListReturnReasonCodesResponse',
            '500.' => 'Amz\\FulfillmentOutbound\\Model\\ListReturnReasonCodesResponse',
            '503.' => 'Amz\\FulfillmentOutbound\\Model\\ListReturnReasonCodesResponse',
        ],
        'createFulfillmentReturn' => [
            '200.' => 'Amz\\FulfillmentOutbound\\Model\\CreateFulfillmentReturnResponse',
            '400.' => 'Amz\\FulfillmentOutbound\\Model\\CreateFulfillmentReturnResponse',
            '401.' => 'Amz\\FulfillmentOutbound\\Model\\CreateFulfillmentReturnResponse',
            '403.' => 'Amz\\FulfillmentOutbound\\Model\\CreateFulfillmentReturnResponse',
            '404.' => 'Amz\\FulfillmentOutbound\\Model\\CreateFulfillmentReturnResponse',
            '429.' => 'Amz\\FulfillmentOutbound\\Model\\CreateFulfillmentReturnResponse',
            '500.' => 'Amz\\FulfillmentOutbound\\Model\\CreateFulfillmentReturnResponse',
            '503.' => 'Amz\\FulfillmentOutbound\\Model\\CreateFulfillmentReturnResponse',
        ],
        'getFulfillmentOrder' => [
            '200.' => 'Amz\\FulfillmentOutbound\\Model\\GetFulfillmentOrderResponse',
            '400.' => 'Amz\\FulfillmentOutbound\\Model\\GetFulfillmentOrderResponse',
            '401.' => 'Amz\\FulfillmentOutbound\\Model\\GetFulfillmentOrderResponse',
            '403.' => 'Amz\\FulfillmentOutbound\\Model\\GetFulfillmentOrderResponse',
            '404.' => 'Amz\\FulfillmentOutbound\\Model\\GetFulfillmentOrderResponse',
            '429.' => 'Amz\\FulfillmentOutbound\\Model\\GetFulfillmentOrderResponse',
            '500.' => 'Amz\\FulfillmentOutbound\\Model\\GetFulfillmentOrderResponse',
            '503.' => 'Amz\\FulfillmentOutbound\\Model\\GetFulfillmentOrderResponse',
        ],
        'updateFulfillmentOrder' => [
            '200.' => 'Amz\\FulfillmentOutbound\\Model\\UpdateFulfillmentOrderResponse',
            '400.' => 'Amz\\FulfillmentOutbound\\Model\\UpdateFulfillmentOrderResponse',
            '401.' => 'Amz\\FulfillmentOutbound\\Model\\UpdateFulfillmentOrderResponse',
            '403.' => 'Amz\\FulfillmentOutbound\\Model\\UpdateFulfillmentOrderResponse',
            '404.' => 'Amz\\FulfillmentOutbound\\Model\\UpdateFulfillmentOrderResponse',
            '429.' => 'Amz\\FulfillmentOutbound\\Model\\UpdateFulfillmentOrderResponse',
            '500.' => 'Amz\\FulfillmentOutbound\\Model\\UpdateFulfillmentOrderResponse',
            '503.' => 'Amz\\FulfillmentOutbound\\Model\\UpdateFulfillmentOrderResponse',
        ],
        'cancelFulfillmentOrder' => [
            '200.' => 'Amz\\FulfillmentOutbound\\Model\\CancelFulfillmentOrderResponse',
            '400.' => 'Amz\\FulfillmentOutbound\\Model\\CancelFulfillmentOrderResponse',
            '401.' => 'Amz\\FulfillmentOutbound\\Model\\CancelFulfillmentOrderResponse',
            '403.' => 'Amz\\FulfillmentOutbound\\Model\\CancelFulfillmentOrderResponse',
            '404.' => 'Amz\\FulfillmentOutbound\\Model\\CancelFulfillmentOrderResponse',
            '429.' => 'Amz\\FulfillmentOutbound\\Model\\CancelFulfillmentOrderResponse',
            '500.' => 'Amz\\FulfillmentOutbound\\Model\\CancelFulfillmentOrderResponse',
            '503.' => 'Amz\\FulfillmentOutbound\\Model\\CancelFulfillmentOrderResponse',
        ],
        'getFeatures' => [
            '200.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeaturesResponse',
            '400.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeaturesResponse',
            '401.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeaturesResponse',
            '403.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeaturesResponse',
            '404.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeaturesResponse',
            '429.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeaturesResponse',
            '500.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeaturesResponse',
            '503.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeaturesResponse',
        ],
        'getFeatureInventory' => [
            '200.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeatureInventoryResponse',
            '400.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeatureInventoryResponse',
            '401.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeatureInventoryResponse',
            '403.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeatureInventoryResponse',
            '404.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeatureInventoryResponse',
            '429.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeatureInventoryResponse',
            '500.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeatureInventoryResponse',
            '503.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeatureInventoryResponse',
        ],
        'getFeatureSKU' => [
            '200.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeatureSkuResponse',
            '400.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeatureSkuResponse',
            '401.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeatureSkuResponse',
            '403.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeatureSkuResponse',
            '404.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeatureSkuResponse',
            '429.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeatureSkuResponse',
            '500.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeatureSkuResponse',
            '503.' => 'Amz\\FulfillmentOutbound\\Model\\GetFeatureSkuResponse',
        ],
        'putListingsItem' => [
            '200.' => 'Amz\\ListingsItems\\Model\\ListingsItemSubmissionResponse',
            '400.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '403.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '413.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '415.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '429.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '500.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '503.' => 'Amz\\ListingsItems\\Model\\ErrorList',
        ],
        'deleteListingsItem' => [
            '200.' => 'Amz\\ListingsItems\\Model\\ListingsItemSubmissionResponse',
            '400.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '403.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '413.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '415.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '429.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '500.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '503.' => 'Amz\\ListingsItems\\Model\\ErrorList',
        ],
        'patchListingsItem' => [
            '200.' => 'Amz\\ListingsItems\\Model\\ListingsItemSubmissionResponse',
            '400.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '403.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '413.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '415.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '429.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '500.' => 'Amz\\ListingsItems\\Model\\ErrorList',
            '503.' => 'Amz\\ListingsItems\\Model\\ErrorList',
        ],
        'getEligibleShipmentServicesOld' => [
            '200.' => 'Amz\\MerchantFulfillment\\Model\\GetEligibleShipmentServicesResponse',
            '400.' => 'Amz\\MerchantFulfillment\\Model\\GetEligibleShipmentServicesResponse',
            '401.' => 'Amz\\MerchantFulfillment\\Model\\GetEligibleShipmentServicesResponse',
            '403.' => 'Amz\\MerchantFulfillment\\Model\\GetEligibleShipmentServicesResponse',
            '404.' => 'Amz\\MerchantFulfillment\\Model\\GetEligibleShipmentServicesResponse',
            '429.' => 'Amz\\MerchantFulfillment\\Model\\GetEligibleShipmentServicesResponse',
            '500.' => 'Amz\\MerchantFulfillment\\Model\\GetEligibleShipmentServicesResponse',
            '503.' => 'Amz\\MerchantFulfillment\\Model\\GetEligibleShipmentServicesResponse',
        ],
        'getEligibleShipmentServices' => [
            '200.' => 'Amz\\MerchantFulfillment\\Model\\GetEligibleShipmentServicesResponse',
            '400.' => 'Amz\\MerchantFulfillment\\Model\\GetEligibleShipmentServicesResponse',
            '401.' => 'Amz\\MerchantFulfillment\\Model\\GetEligibleShipmentServicesResponse',
            '403.' => 'Amz\\MerchantFulfillment\\Model\\GetEligibleShipmentServicesResponse',
            '404.' => 'Amz\\MerchantFulfillment\\Model\\GetEligibleShipmentServicesResponse',
            '429.' => 'Amz\\MerchantFulfillment\\Model\\GetEligibleShipmentServicesResponse',
            '500.' => 'Amz\\MerchantFulfillment\\Model\\GetEligibleShipmentServicesResponse',
            '503.' => 'Amz\\MerchantFulfillment\\Model\\GetEligibleShipmentServicesResponse',
        ],
        'getShipment' => [
            '200.' => 'Amz\\MerchantFulfillment\\Model\\GetShipmentResponse',
            '400.' => 'Amz\\MerchantFulfillment\\Model\\GetShipmentResponse',
            '401.' => 'Amz\\MerchantFulfillment\\Model\\GetShipmentResponse',
            '403.' => 'Amz\\MerchantFulfillment\\Model\\GetShipmentResponse',
            '404.' => 'Amz\\MerchantFulfillment\\Model\\GetShipmentResponse',
            '429.' => 'Amz\\MerchantFulfillment\\Model\\GetShipmentResponse',
            '500.' => 'Amz\\MerchantFulfillment\\Model\\GetShipmentResponse',
            '503.' => 'Amz\\MerchantFulfillment\\Model\\GetShipmentResponse',
        ],
        'cancelShipment' => [
            '200.' => 'Amz\\MerchantFulfillment\\Model\\CancelShipmentResponse',
            '400.' => 'Amz\\MerchantFulfillment\\Model\\CancelShipmentResponse',
            '401.' => 'Amz\\MerchantFulfillment\\Model\\CancelShipmentResponse',
            '403.' => 'Amz\\MerchantFulfillment\\Model\\CancelShipmentResponse',
            '404.' => 'Amz\\MerchantFulfillment\\Model\\CancelShipmentResponse',
            '429.' => 'Amz\\MerchantFulfillment\\Model\\CancelShipmentResponse',
            '500.' => 'Amz\\MerchantFulfillment\\Model\\CancelShipmentResponse',
            '503.' => 'Amz\\MerchantFulfillment\\Model\\CancelShipmentResponse',
        ],
        'cancelShipmentOld' => [
            '200.' => 'Amz\\MerchantFulfillment\\Model\\CancelShipmentResponse',
            '400.' => 'Amz\\MerchantFulfillment\\Model\\CancelShipmentResponse',
            '401.' => 'Amz\\MerchantFulfillment\\Model\\CancelShipmentResponse',
            '403.' => 'Amz\\MerchantFulfillment\\Model\\CancelShipmentResponse',
            '404.' => 'Amz\\MerchantFulfillment\\Model\\CancelShipmentResponse',
            '429.' => 'Amz\\MerchantFulfillment\\Model\\CancelShipmentResponse',
            '500.' => 'Amz\\MerchantFulfillment\\Model\\CancelShipmentResponse',
            '503.' => 'Amz\\MerchantFulfillment\\Model\\CancelShipmentResponse',
        ],
        'createShipment' => [
            '200.' => 'Amz\\MerchantFulfillment\\Model\\CreateShipmentResponse',
            '400.' => 'Amz\\MerchantFulfillment\\Model\\CreateShipmentResponse',
            '401.' => 'Amz\\MerchantFulfillment\\Model\\CreateShipmentResponse',
            '403.' => 'Amz\\MerchantFulfillment\\Model\\CreateShipmentResponse',
            '404.' => 'Amz\\MerchantFulfillment\\Model\\CreateShipmentResponse',
            '429.' => 'Amz\\MerchantFulfillment\\Model\\CreateShipmentResponse',
            '500.' => 'Amz\\MerchantFulfillment\\Model\\CreateShipmentResponse',
            '503.' => 'Amz\\MerchantFulfillment\\Model\\CreateShipmentResponse',
        ],
        'getAdditionalSellerInputsOld' => [
            '200.' => 'Amz\\MerchantFulfillment\\Model\\GetAdditionalSellerInputsResponse',
            '400.' => 'Amz\\MerchantFulfillment\\Model\\GetAdditionalSellerInputsResponse',
            '401.' => 'Amz\\MerchantFulfillment\\Model\\GetAdditionalSellerInputsResponse',
            '403.' => 'Amz\\MerchantFulfillment\\Model\\GetAdditionalSellerInputsResponse',
            '404.' => 'Amz\\MerchantFulfillment\\Model\\GetAdditionalSellerInputsResponse',
            '429.' => 'Amz\\MerchantFulfillment\\Model\\GetAdditionalSellerInputsResponse',
            '500.' => 'Amz\\MerchantFulfillment\\Model\\GetAdditionalSellerInputsResponse',
            '503.' => 'Amz\\MerchantFulfillment\\Model\\GetAdditionalSellerInputsResponse',
        ],
        'getAdditionalSellerInputs' => [
            '200.' => 'Amz\\MerchantFulfillment\\Model\\GetAdditionalSellerInputsResponse',
            '400.' => 'Amz\\MerchantFulfillment\\Model\\GetAdditionalSellerInputsResponse',
            '401.' => 'Amz\\MerchantFulfillment\\Model\\GetAdditionalSellerInputsResponse',
            '403.' => 'Amz\\MerchantFulfillment\\Model\\GetAdditionalSellerInputsResponse',
            '404.' => 'Amz\\MerchantFulfillment\\Model\\GetAdditionalSellerInputsResponse',
            '429.' => 'Amz\\MerchantFulfillment\\Model\\GetAdditionalSellerInputsResponse',
            '500.' => 'Amz\\MerchantFulfillment\\Model\\GetAdditionalSellerInputsResponse',
            '503.' => 'Amz\\MerchantFulfillment\\Model\\GetAdditionalSellerInputsResponse',
        ],
        'getMessagingActionsForOrder' => [
            '200.' => 'Amz\\Messaging\\Model\\GetMessagingActionsForOrderResponse',
            '400.' => 'Amz\\Messaging\\Model\\GetMessagingActionsForOrderResponse',
            '403.' => 'Amz\\Messaging\\Model\\GetMessagingActionsForOrderResponse',
            '404.' => 'Amz\\Messaging\\Model\\GetMessagingActionsForOrderResponse',
            '413.' => 'Amz\\Messaging\\Model\\GetMessagingActionsForOrderResponse',
            '415.' => 'Amz\\Messaging\\Model\\GetMessagingActionsForOrderResponse',
            '429.' => 'Amz\\Messaging\\Model\\GetMessagingActionsForOrderResponse',
            '500.' => 'Amz\\Messaging\\Model\\GetMessagingActionsForOrderResponse',
            '503.' => 'Amz\\Messaging\\Model\\GetMessagingActionsForOrderResponse',
        ],
        'confirmCustomizationDetails' => [
            '201.' => 'Amz\\Messaging\\Model\\CreateConfirmCustomizationDetailsResponse',
            '400.' => 'Amz\\Messaging\\Model\\CreateConfirmCustomizationDetailsResponse',
            '403.' => 'Amz\\Messaging\\Model\\CreateConfirmCustomizationDetailsResponse',
            '404.' => 'Amz\\Messaging\\Model\\CreateConfirmCustomizationDetailsResponse',
            '413.' => 'Amz\\Messaging\\Model\\CreateConfirmCustomizationDetailsResponse',
            '415.' => 'Amz\\Messaging\\Model\\CreateConfirmCustomizationDetailsResponse',
            '429.' => 'Amz\\Messaging\\Model\\CreateConfirmCustomizationDetailsResponse',
            '500.' => 'Amz\\Messaging\\Model\\CreateConfirmCustomizationDetailsResponse',
            '503.' => 'Amz\\Messaging\\Model\\CreateConfirmCustomizationDetailsResponse',
        ],
        'createConfirmDeliveryDetails' => [
            '201.' => 'Amz\\Messaging\\Model\\CreateConfirmDeliveryDetailsResponse',
            '400.' => 'Amz\\Messaging\\Model\\CreateConfirmDeliveryDetailsResponse',
            '403.' => 'Amz\\Messaging\\Model\\CreateConfirmDeliveryDetailsResponse',
            '404.' => 'Amz\\Messaging\\Model\\CreateConfirmDeliveryDetailsResponse',
            '413.' => 'Amz\\Messaging\\Model\\CreateConfirmDeliveryDetailsResponse',
            '415.' => 'Amz\\Messaging\\Model\\CreateConfirmDeliveryDetailsResponse',
            '429.' => 'Amz\\Messaging\\Model\\CreateConfirmDeliveryDetailsResponse',
            '500.' => 'Amz\\Messaging\\Model\\CreateConfirmDeliveryDetailsResponse',
            '503.' => 'Amz\\Messaging\\Model\\CreateConfirmDeliveryDetailsResponse',
        ],
        'createLegalDisclosure' => [
            '201.' => 'Amz\\Messaging\\Model\\CreateLegalDisclosureResponse',
            '400.' => 'Amz\\Messaging\\Model\\CreateLegalDisclosureResponse',
            '403.' => 'Amz\\Messaging\\Model\\CreateLegalDisclosureResponse',
            '404.' => 'Amz\\Messaging\\Model\\CreateLegalDisclosureResponse',
            '413.' => 'Amz\\Messaging\\Model\\CreateLegalDisclosureResponse',
            '415.' => 'Amz\\Messaging\\Model\\CreateLegalDisclosureResponse',
            '429.' => 'Amz\\Messaging\\Model\\CreateLegalDisclosureResponse',
            '500.' => 'Amz\\Messaging\\Model\\CreateLegalDisclosureResponse',
            '503.' => 'Amz\\Messaging\\Model\\CreateLegalDisclosureResponse',
        ],
        'createNegativeFeedbackRemoval' => [
            '201.' => 'Amz\\Messaging\\Model\\CreateNegativeFeedbackRemovalResponse',
            '400.' => 'Amz\\Messaging\\Model\\CreateNegativeFeedbackRemovalResponse',
            '403.' => 'Amz\\Messaging\\Model\\CreateNegativeFeedbackRemovalResponse',
            '404.' => 'Amz\\Messaging\\Model\\CreateNegativeFeedbackRemovalResponse',
            '413.' => 'Amz\\Messaging\\Model\\CreateNegativeFeedbackRemovalResponse',
            '415.' => 'Amz\\Messaging\\Model\\CreateNegativeFeedbackRemovalResponse',
            '429.' => 'Amz\\Messaging\\Model\\CreateNegativeFeedbackRemovalResponse',
            '500.' => 'Amz\\Messaging\\Model\\CreateNegativeFeedbackRemovalResponse',
            '503.' => 'Amz\\Messaging\\Model\\CreateNegativeFeedbackRemovalResponse',
        ],
        'createConfirmOrderDetails' => [
            '201.' => 'Amz\\Messaging\\Model\\CreateConfirmOrderDetailsResponse',
            '400.' => 'Amz\\Messaging\\Model\\CreateConfirmOrderDetailsResponse',
            '403.' => 'Amz\\Messaging\\Model\\CreateConfirmOrderDetailsResponse',
            '404.' => 'Amz\\Messaging\\Model\\CreateConfirmOrderDetailsResponse',
            '413.' => 'Amz\\Messaging\\Model\\CreateConfirmOrderDetailsResponse',
            '415.' => 'Amz\\Messaging\\Model\\CreateConfirmOrderDetailsResponse',
            '429.' => 'Amz\\Messaging\\Model\\CreateConfirmOrderDetailsResponse',
            '500.' => 'Amz\\Messaging\\Model\\CreateConfirmOrderDetailsResponse',
            '503.' => 'Amz\\Messaging\\Model\\CreateConfirmOrderDetailsResponse',
        ],
        'createConfirmServiceDetails' => [
            '201.' => 'Amz\\Messaging\\Model\\CreateConfirmServiceDetailsResponse',
            '400.' => 'Amz\\Messaging\\Model\\CreateConfirmServiceDetailsResponse',
            '403.' => 'Amz\\Messaging\\Model\\CreateConfirmServiceDetailsResponse',
            '404.' => 'Amz\\Messaging\\Model\\CreateConfirmServiceDetailsResponse',
            '413.' => 'Amz\\Messaging\\Model\\CreateConfirmServiceDetailsResponse',
            '415.' => 'Amz\\Messaging\\Model\\CreateConfirmServiceDetailsResponse',
            '429.' => 'Amz\\Messaging\\Model\\CreateConfirmServiceDetailsResponse',
            '500.' => 'Amz\\Messaging\\Model\\CreateConfirmServiceDetailsResponse',
            '503.' => 'Amz\\Messaging\\Model\\CreateConfirmServiceDetailsResponse',
        ],
        'CreateAmazonMotors' => [
            '201.' => 'Amz\\Messaging\\Model\\CreateAmazonMotorsResponse',
            '400.' => 'Amz\\Messaging\\Model\\CreateAmazonMotorsResponse',
            '403.' => 'Amz\\Messaging\\Model\\CreateAmazonMotorsResponse',
            '404.' => 'Amz\\Messaging\\Model\\CreateAmazonMotorsResponse',
            '413.' => 'Amz\\Messaging\\Model\\CreateAmazonMotorsResponse',
            '415.' => 'Amz\\Messaging\\Model\\CreateAmazonMotorsResponse',
            '429.' => 'Amz\\Messaging\\Model\\CreateAmazonMotorsResponse',
            '500.' => 'Amz\\Messaging\\Model\\CreateAmazonMotorsResponse',
            '503.' => 'Amz\\Messaging\\Model\\CreateAmazonMotorsResponse',
        ],
        'CreateWarranty' => [
            '201.' => 'Amz\\Messaging\\Model\\CreateWarrantyResponse',
            '400.' => 'Amz\\Messaging\\Model\\CreateWarrantyResponse',
            '403.' => 'Amz\\Messaging\\Model\\CreateWarrantyResponse',
            '404.' => 'Amz\\Messaging\\Model\\CreateWarrantyResponse',
            '413.' => 'Amz\\Messaging\\Model\\CreateWarrantyResponse',
            '415.' => 'Amz\\Messaging\\Model\\CreateWarrantyResponse',
            '429.' => 'Amz\\Messaging\\Model\\CreateWarrantyResponse',
            '500.' => 'Amz\\Messaging\\Model\\CreateWarrantyResponse',
            '503.' => 'Amz\\Messaging\\Model\\CreateWarrantyResponse',
        ],
        'GetAttributes' => [
            '200.' => 'Amz\\Messaging\\Model\\GetAttributesResponse',
            '400.' => 'Amz\\Messaging\\Model\\GetAttributesResponse',
            '403.' => 'Amz\\Messaging\\Model\\GetAttributesResponse',
            '404.' => 'Amz\\Messaging\\Model\\GetAttributesResponse',
            '413.' => 'Amz\\Messaging\\Model\\GetAttributesResponse',
            '415.' => 'Amz\\Messaging\\Model\\GetAttributesResponse',
            '429.' => 'Amz\\Messaging\\Model\\GetAttributesResponse',
            '500.' => 'Amz\\Messaging\\Model\\GetAttributesResponse',
            '503.' => 'Amz\\Messaging\\Model\\GetAttributesResponse',
        ],
        'createDigitalAccessKey' => [
            '201.' => 'Amz\\Messaging\\Model\\CreateDigitalAccessKeyResponse',
            '400.' => 'Amz\\Messaging\\Model\\CreateDigitalAccessKeyResponse',
            '403.' => 'Amz\\Messaging\\Model\\CreateDigitalAccessKeyResponse',
            '404.' => 'Amz\\Messaging\\Model\\CreateDigitalAccessKeyResponse',
            '413.' => 'Amz\\Messaging\\Model\\CreateDigitalAccessKeyResponse',
            '415.' => 'Amz\\Messaging\\Model\\CreateDigitalAccessKeyResponse',
            '429.' => 'Amz\\Messaging\\Model\\CreateDigitalAccessKeyResponse',
            '500.' => 'Amz\\Messaging\\Model\\CreateDigitalAccessKeyResponse',
            '503.' => 'Amz\\Messaging\\Model\\CreateDigitalAccessKeyResponse',
        ],
        'createUnexpectedProblem' => [
            '201.' => 'Amz\\Messaging\\Model\\CreateUnexpectedProblemResponse',
            '400.' => 'Amz\\Messaging\\Model\\CreateUnexpectedProblemResponse',
            '403.' => 'Amz\\Messaging\\Model\\CreateUnexpectedProblemResponse',
            '404.' => 'Amz\\Messaging\\Model\\CreateUnexpectedProblemResponse',
            '413.' => 'Amz\\Messaging\\Model\\CreateUnexpectedProblemResponse',
            '415.' => 'Amz\\Messaging\\Model\\CreateUnexpectedProblemResponse',
            '429.' => 'Amz\\Messaging\\Model\\CreateUnexpectedProblemResponse',
            '500.' => 'Amz\\Messaging\\Model\\CreateUnexpectedProblemResponse',
            '503.' => 'Amz\\Messaging\\Model\\CreateUnexpectedProblemResponse',
        ],
        'getSubscription' => [
            '200.' => 'Amz\\Notifications\\Model\\GetSubscriptionResponse',
            '400.' => 'Amz\\Notifications\\Model\\GetSubscriptionResponse',
            '403.' => 'Amz\\Notifications\\Model\\GetSubscriptionResponse',
            '404.' => 'Amz\\Notifications\\Model\\GetSubscriptionResponse',
            '413.' => 'Amz\\Notifications\\Model\\GetSubscriptionResponse',
            '415.' => 'Amz\\Notifications\\Model\\GetSubscriptionResponse',
            '429.' => 'Amz\\Notifications\\Model\\GetSubscriptionResponse',
            '500.' => 'Amz\\Notifications\\Model\\GetSubscriptionResponse',
            '503.' => 'Amz\\Notifications\\Model\\GetSubscriptionResponse',
        ],
        'createSubscription' => [
            '200.' => 'Amz\\Notifications\\Model\\CreateSubscriptionResponse',
            '400.' => 'Amz\\Notifications\\Model\\CreateSubscriptionResponse',
            '403.' => 'Amz\\Notifications\\Model\\CreateSubscriptionResponse',
            '404.' => 'Amz\\Notifications\\Model\\CreateSubscriptionResponse',
            '409.' => 'Amz\\Notifications\\Model\\CreateSubscriptionResponse',
            '413.' => 'Amz\\Notifications\\Model\\CreateSubscriptionResponse',
            '415.' => 'Amz\\Notifications\\Model\\CreateSubscriptionResponse',
            '429.' => 'Amz\\Notifications\\Model\\CreateSubscriptionResponse',
            '500.' => 'Amz\\Notifications\\Model\\CreateSubscriptionResponse',
            '503.' => 'Amz\\Notifications\\Model\\CreateSubscriptionResponse',
        ],
        'getSubscriptionById' => [
            '200.' => 'Amz\\Notifications\\Model\\GetSubscriptionByIdResponse',
            '400.' => 'Amz\\Notifications\\Model\\GetSubscriptionByIdResponse',
            '403.' => 'Amz\\Notifications\\Model\\GetSubscriptionByIdResponse',
            '404.' => 'Amz\\Notifications\\Model\\GetSubscriptionResponse',
            '409.' => 'Amz\\Notifications\\Model\\GetSubscriptionByIdResponse',
            '413.' => 'Amz\\Notifications\\Model\\GetSubscriptionByIdResponse',
            '415.' => 'Amz\\Notifications\\Model\\GetSubscriptionByIdResponse',
            '429.' => 'Amz\\Notifications\\Model\\GetSubscriptionByIdResponse',
            '500.' => 'Amz\\Notifications\\Model\\GetSubscriptionByIdResponse',
            '503.' => 'Amz\\Notifications\\Model\\GetSubscriptionByIdResponse',
        ],
        'deleteSubscriptionById' => [
            '200.' => 'Amz\\Notifications\\Model\\DeleteSubscriptionByIdResponse',
            '400.' => 'Amz\\Notifications\\Model\\DeleteSubscriptionByIdResponse',
            '403.' => 'Amz\\Notifications\\Model\\DeleteSubscriptionByIdResponse',
            '404.' => 'Amz\\Notifications\\Model\\DeleteSubscriptionByIdResponse',
            '409.' => 'Amz\\Notifications\\Model\\DeleteSubscriptionByIdResponse',
            '413.' => 'Amz\\Notifications\\Model\\DeleteSubscriptionByIdResponse',
            '415.' => 'Amz\\Notifications\\Model\\DeleteSubscriptionByIdResponse',
            '429.' => 'Amz\\Notifications\\Model\\DeleteSubscriptionByIdResponse',
            '500.' => 'Amz\\Notifications\\Model\\DeleteSubscriptionByIdResponse',
            '503.' => 'Amz\\Notifications\\Model\\DeleteSubscriptionByIdResponse',
        ],
        'getDestinations' => [
            '200.' => 'Amz\\Notifications\\Model\\GetDestinationsResponse',
            '400.' => 'Amz\\Notifications\\Model\\GetDestinationsResponse',
            '403.' => 'Amz\\Notifications\\Model\\GetDestinationsResponse',
            '404.' => 'Amz\\Notifications\\Model\\GetDestinationsResponse',
            '409.' => 'Amz\\Notifications\\Model\\GetDestinationsResponse',
            '413.' => 'Amz\\Notifications\\Model\\GetDestinationsResponse',
            '415.' => 'Amz\\Notifications\\Model\\GetDestinationsResponse',
            '429.' => 'Amz\\Notifications\\Model\\GetDestinationsResponse',
            '500.' => 'Amz\\Notifications\\Model\\GetDestinationsResponse',
            '503.' => 'Amz\\Notifications\\Model\\GetDestinationsResponse',
        ],
        'createDestination' => [
            '200.' => 'Amz\\Notifications\\Model\\CreateDestinationResponse',
            '400.' => 'Amz\\Notifications\\Model\\CreateDestinationResponse',
            '403.' => 'Amz\\Notifications\\Model\\CreateDestinationResponse',
            '404.' => 'Amz\\Notifications\\Model\\CreateDestinationResponse',
            '409.' => 'Amz\\Notifications\\Model\\CreateDestinationResponse',
            '413.' => 'Amz\\Notifications\\Model\\CreateDestinationResponse',
            '415.' => 'Amz\\Notifications\\Model\\CreateDestinationResponse',
            '429.' => 'Amz\\Notifications\\Model\\CreateDestinationResponse',
            '500.' => 'Amz\\Notifications\\Model\\CreateDestinationResponse',
            '503.' => 'Amz\\Notifications\\Model\\CreateDestinationResponse',
        ],
        'getDestination' => [
            '200.' => 'Amz\\Notifications\\Model\\GetDestinationResponse',
            '400.' => 'Amz\\Notifications\\Model\\GetDestinationResponse',
            '403.' => 'Amz\\Notifications\\Model\\GetDestinationResponse',
            '404.' => 'Amz\\Notifications\\Model\\GetDestinationResponse',
            '409.' => 'Amz\\Notifications\\Model\\GetDestinationResponse',
            '413.' => 'Amz\\Notifications\\Model\\GetDestinationResponse',
            '415.' => 'Amz\\Notifications\\Model\\GetDestinationResponse',
            '429.' => 'Amz\\Notifications\\Model\\GetDestinationResponse',
            '500.' => 'Amz\\Notifications\\Model\\GetDestinationResponse',
            '503.' => 'Amz\\Notifications\\Model\\GetDestinationResponse',
        ],
        'deleteDestination' => [
            '200.' => 'Amz\\Notifications\\Model\\DeleteDestinationResponse',
            '400.' => 'Amz\\Notifications\\Model\\DeleteDestinationResponse',
            '403.' => 'Amz\\Notifications\\Model\\DeleteDestinationResponse',
            '404.' => 'Amz\\Notifications\\Model\\DeleteDestinationResponse',
            '409.' => 'Amz\\Notifications\\Model\\DeleteDestinationResponse',
            '413.' => 'Amz\\Notifications\\Model\\DeleteDestinationResponse',
            '415.' => 'Amz\\Notifications\\Model\\DeleteDestinationResponse',
            '429.' => 'Amz\\Notifications\\Model\\DeleteDestinationResponse',
            '500.' => 'Amz\\Notifications\\Model\\DeleteDestinationResponse',
            '503.' => 'Amz\\Notifications\\Model\\DeleteDestinationResponse',
        ],
        'getOrders' => [
            '200.' => 'Amz\\Orders\\Model\\GetOrdersResponse',
            '400.' => 'Amz\\Orders\\Model\\GetOrdersResponse',
            '403.' => 'Amz\\Orders\\Model\\GetOrdersResponse',
            '404.' => 'Amz\\Orders\\Model\\GetOrdersResponse',
            '429.' => 'Amz\\Orders\\Model\\GetOrdersResponse',
            '500.' => 'Amz\\Orders\\Model\\GetOrdersResponse',
            '503.' => 'Amz\\Orders\\Model\\GetOrdersResponse',
        ],
        'getOrder' => [
            '200.' => 'Amz\\Orders\\Model\\GetOrderResponse',
            '400.' => 'Amz\\Orders\\Model\\GetOrderResponse',
            '403.' => 'Amz\\Orders\\Model\\GetOrderResponse',
            '404.' => 'Amz\\Orders\\Model\\GetOrderResponse',
            '429.' => 'Amz\\Orders\\Model\\GetOrderResponse',
            '500.' => 'Amz\\Orders\\Model\\GetOrderResponse',
            '503.' => 'Amz\\Orders\\Model\\GetOrderResponse',
        ],
        'getOrderBuyerInfo' => [
            '200.' => 'Amz\\Orders\\Model\\GetOrderBuyerInfoResponse',
            '400.' => 'Amz\\Orders\\Model\\GetOrderBuyerInfoResponse',
            '403.' => 'Amz\\Orders\\Model\\GetOrderBuyerInfoResponse',
            '404.' => 'Amz\\Orders\\Model\\GetOrderBuyerInfoResponse',
            '429.' => 'Amz\\Orders\\Model\\GetOrderBuyerInfoResponse',
            '500.' => 'Amz\\Orders\\Model\\GetOrderBuyerInfoResponse',
            '503.' => 'Amz\\Orders\\Model\\GetOrderBuyerInfoResponse',
        ],
        'getOrderAddress' => [
            '200.' => 'Amz\\Orders\\Model\\GetOrderAddressResponse',
            '400.' => 'Amz\\Orders\\Model\\GetOrderAddressResponse',
            '403.' => 'Amz\\Orders\\Model\\GetOrderAddressResponse',
            '404.' => 'Amz\\Orders\\Model\\GetOrderAddressResponse',
            '429.' => 'Amz\\Orders\\Model\\GetOrderAddressResponse',
            '500.' => 'Amz\\Orders\\Model\\GetOrderAddressResponse',
            '503.' => 'Amz\\Orders\\Model\\GetOrderAddressResponse',
        ],
        'getOrderItems' => [
            '200.' => 'Amz\\Orders\\Model\\GetOrderItemsResponse',
            '400.' => 'Amz\\Orders\\Model\\GetOrderItemsResponse',
            '403.' => 'Amz\\Orders\\Model\\GetOrderItemsResponse',
            '404.' => 'Amz\\Orders\\Model\\GetOrderItemsResponse',
            '429.' => 'Amz\\Orders\\Model\\GetOrderItemsResponse',
            '500.' => 'Amz\\Orders\\Model\\GetOrderItemsResponse',
            '503.' => 'Amz\\Orders\\Model\\GetOrderItemsResponse',
        ],
        'getOrderItemsBuyerInfo' => [
            '200.' => 'Amz\\Orders\\Model\\GetOrderItemsBuyerInfoResponse',
            '400.' => 'Amz\\Orders\\Model\\GetOrderItemsBuyerInfoResponse',
            '403.' => 'Amz\\Orders\\Model\\GetOrderItemsBuyerInfoResponse',
            '404.' => 'Amz\\Orders\\Model\\GetOrderItemsBuyerInfoResponse',
            '429.' => 'Amz\\Orders\\Model\\GetOrderItemsBuyerInfoResponse',
            '500.' => 'Amz\\Orders\\Model\\GetOrderItemsBuyerInfoResponse',
            '503.' => 'Amz\\Orders\\Model\\GetOrderItemsBuyerInfoResponse',
        ],
    ];
}
